# Generated by Django 3.0.7 on 2020-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=40)),
                ('member1', models.TextField(max_length=50)),
                ('member2', models.TextField(max_length=50)),
                ('member3', models.TextField(max_length=50)),
                ('member4', models.TextField(max_length=50)),
            ],
        ),
    ]
