# Generated by Django 3.0.7 on 2020-06-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
