# Generated by Django 3.0.7 on 2020-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200623_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='member2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='member3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='member4',
            field=models.CharField(max_length=50),
        ),
    ]
